[package]
name = "kitchentimer"
version = "0.0.1"
authors = ["shy <shy@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
signal-hook = "0.3.8"
